version: "3"

services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.0-25.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    env_file: .env
    volumes:
      - dcm4chee-arc_ldap:/var/lib/openldap/openldap-data
      - dcm4chee-arc_slapd.d:/etc/openldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:14.1-25
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - dcm4chee-arc_db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.25.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: .env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - dcm4chee-arc_wildfly:/opt/wildfly/standalone
      - dcm4chee-arc_storage:/storage
  ohif:
    image: ohif/viewer:v4.12.22.18589
    ports:
      - "3000:80"
    volumes:
      - ohif:/usr/share/nginx/html/
  niffler:
    image: niffler
    ports:
      - "5000:5000"
      
volumes:
  ohif:
    name: ohif
    external: true
  
  dcm4chee-arc_ldap:
  dcm4chee-arc_slapd.d:

  dcm4chee-arc_db:

  dcm4chee-arc_wildfly:
  dcm4chee-arc_storage: